import type { Profile } from './profile.model';

// Language-specific default profiles.
// 관심사·인트로는 본인 직접 입력값(홈 카드의 Firestore 데이터)과 일치하도록 유지.
// 다국어 번역은 짧은 사실 한 줄로 통일 — 검증되지 않은 일반 문구를 박지 않음.
export const DEFAULT_PROFILES: Record<string, Profile> = {
  en: {
    name: 'Yeojunsu',
    tagline: 'Student Developer',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Swimming', 'Table tennis', 'Reading', 'Chess'],
    intro: ['Student developer.'],
    region: 'Nowon-gu Wolgyedong, Seoul, South Korea',
  },
  ko: {
    name: '여준수',
    tagline: '대학생 개발자',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['수영', '탁구', '독서', '체스'],
    intro: ['대학생 개발자입니다.'],
    region: '서울 노원구 월계동',
  },
  ja: {
    name: '여준수 (ヨ・ジュンス)',
    tagline: '大学生開発者',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['水泳', '卓球', '読書', 'チェス'],
    intro: ['大学生開発者です。'],
    region: 'ソウル蘆原区月渓洞, 韓国',
  },
  zh: {
    name: '余俊秀',
    tagline: '大学生开发者',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['游泳', '乒乓球', '阅读', '国际象棋'],
    intro: ['大学生开发者。'],
    region: '首尔芦原区月桂洞，韩国',
  },
  es: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Estudiante desarrollador',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Natación', 'Tenis de mesa', 'Lectura', 'Ajedrez'],
    intro: ['Estudiante desarrollador.'],
    region: 'Seúl, Corea del Sur',
  },
  fr: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Étudiant développeur',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Natation', 'Tennis de table', 'Lecture', 'Échecs'],
    intro: ['Étudiant développeur.'],
    region: 'Séoul, Corée du Sud',
  },
  de: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Studentischer Entwickler',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Schwimmen', 'Tischtennis', 'Lesen', 'Schach'],
    intro: ['Studentischer Entwickler.'],
    region: 'Seoul, Südkorea',
  },
  pt: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Estudante desenvolvedor',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Natação', 'Tênis de mesa', 'Leitura', 'Xadrez'],
    intro: ['Estudante desenvolvedor.'],
    region: 'Seul, Coreia do Sul',
  },
  ru: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Студент-разработчик',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: ['Плавание', 'Настольный теннис', 'Чтение', 'Шахматы'],
    intro: ['Студент-разработчик.'],
    region: 'Сеул, Южная Корея',
  },
};
