import type { Profile } from './profile.model';

// Language-specific default profiles.
// 관심사·인트로는 본인 직접 입력값(홈 카드의 Firestore 데이터)과 일치하도록 유지.
// 다국어 번역은 짧은 사실 한 줄로 통일 — 검증되지 않은 일반 문구를 박지 않음.
export const DEFAULT_PROFILES: Record<string, Profile> = {
  en: {
    name: 'Yeojunsu',
    tagline: 'Student Developer',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Swimming (beginner)',
      'Table tennis (shakehand)',
      'Reading (self-help · 1–2/mo)',
      'Chess (~1200)',
    ],
    intro: ['Student developer.'],
    region: 'Nowon-gu Wolgyedong, Seoul, South Korea',
    motivation: 'I get to build the tools I want to use myself.',
    values: ['Honesty', 'Autonomy', 'Curiosity', 'Consistency'],
    goal: 'Ship a side project with real users.',
  },
  ko: {
    name: '여준수',
    tagline: '대학생 개발자',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      '수영 (초보)',
      '탁구 (셰이크핸드)',
      '독서 (자기계발 · 월1~2권)',
      '체스 (~1200)',
    ],
    intro: ['대학생 개발자입니다.'],
    region: '서울 노원구 월계동',
    motivation: '내가 쓸 도구를 직접 만들 수 있어서.',
    values: ['정직함', '자율성', '호기심', '꾸준함'],
    goal: '사용자가 있는 토이 프로젝트 출시.',
  },
  ja: {
    name: '여준수 (ヨ・ジュンス)',
    tagline: '大学生開発者',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      '水泳 (初級)',
      '卓球 (シェークハンド)',
      '読書 (自己啓発 · 月1〜2冊)',
      'チェス (~1200)',
    ],
    intro: ['大学生開発者です。'],
    region: 'ソウル蘆原区月渓洞, 韓国',
    motivation: '自分が使うツールを自分で作れるから。',
    values: ['誠実さ', '自律', '好奇心', '継続'],
    goal: '実ユーザーがいる個人プロジェクトのリリース。',
  },
  zh: {
    name: '余俊秀',
    tagline: '大学生开发者',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      '游泳 (初学)',
      '乒乓球 (横拍)',
      '阅读 (自我提升 · 月1~2本)',
      '国际象棋 (~1200)',
    ],
    intro: ['大学生开发者。'],
    region: '首尔芦原区月桂洞，韩国',
    motivation: '能亲手做出自己想用的工具。',
    values: ['诚实', '自主', '好奇', '坚持'],
    goal: '发布有真实用户的个人项目。',
  },
  es: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Estudiante desarrollador',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Natación (principiante)',
      'Tenis de mesa (shakehand)',
      'Lectura (autoayuda · 1–2/mes)',
      'Ajedrez (~1200)',
    ],
    intro: ['Estudiante desarrollador.'],
    region: 'Seúl, Corea del Sur',
    motivation: 'Puedo crear las herramientas que quiero usar.',
    values: ['Honestidad', 'Autonomía', 'Curiosidad', 'Constancia'],
    goal: 'Lanzar un proyecto personal con usuarios reales.',
  },
  fr: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Étudiant développeur',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Natation (débutant)',
      'Tennis de table (shakehand)',
      'Lecture (dév. perso · 1–2/mois)',
      'Échecs (~1200)',
    ],
    intro: ['Étudiant développeur.'],
    region: 'Séoul, Corée du Sud',
    motivation: 'Je peux créer moi-même les outils que j’utilise.',
    values: ['Honnêteté', 'Autonomie', 'Curiosité', 'Constance'],
    goal: 'Lancer un projet personnel avec de vrais utilisateurs.',
  },
  de: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Studentischer Entwickler',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Schwimmen (Anfänger)',
      'Tischtennis (Shakehand)',
      'Lesen (Selbsthilfe · 1–2/Monat)',
      'Schach (~1200)',
    ],
    intro: ['Studentischer Entwickler.'],
    region: 'Seoul, Südkorea',
    motivation: 'Ich kann die Werkzeuge selbst bauen, die ich nutzen will.',
    values: ['Ehrlichkeit', 'Autonomie', 'Neugier', 'Beständigkeit'],
    goal: 'Ein eigenes Projekt mit echten Nutzern veröffentlichen.',
  },
  pt: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Estudante desenvolvedor',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Natação (iniciante)',
      'Tênis de mesa (shakehand)',
      'Leitura (autoajuda · 1–2/mês)',
      'Xadrez (~1200)',
    ],
    intro: ['Estudante desenvolvedor.'],
    region: 'Seul, Coreia do Sul',
    motivation: 'Posso criar as ferramentas que quero usar.',
    values: ['Honestidade', 'Autonomia', 'Curiosidade', 'Constância'],
    goal: 'Lançar um projeto pessoal com usuários reais.',
  },
  ru: {
    name: 'Yeojunsu (여준수)',
    tagline: 'Студент-разработчик',
    email: 'yeojoonsoo02@gmail.com',
    photo: '/profile.jpg',
    interests: [
      'Плавание (начинающий)',
      'Настольный теннис (шейкхэнд)',
      'Чтение (саморазвитие · 1–2/мес)',
      'Шахматы (~1200)',
    ],
    intro: ['Студент-разработчик.'],
    region: 'Сеул, Южная Корея',
    motivation: 'Могу сам создавать инструменты, которыми пользуюсь.',
    values: ['Честность', 'Автономия', 'Любознательность', 'Постоянство'],
    goal: 'Выпустить личный проект с реальными пользователями.',
  },
};
