import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/lib/AuthProvider";
import I18nProvider from "@/lib/I18nProvider";
import LanguageSwitcher from "@/features/lang/LanguageSwitcher";
import '@/lib/i18n';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased relative">
        <AuthProvider>
          <I18nProvider>
            <div className="fixed top-2 right-4 z-50">
              <LanguageSwitcher />
            </div>
            {children}
          </I18nProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
